on:
  push:
    paths:
      - "apps/identity-svc/**"
      - "apps/account-svc/**"
      - "apps/oauth-svc/**"
      - "apps/confirmation-of-payee-svc/**"
      - "apps/payment-svc/**"
      - "apps/ledger-svc/**"
      - "apps/merchant-svc/**"
      - "apps/api-server/**"
      - ".github/workflows/api-server.yaml"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf generate apps/identity-svc --include-imports --template apps/identity-svc/buf.gen.yaml --output apps/identity-svc
      - run: buf generate apps/account-svc --include-imports --template apps/account-svc/buf.gen.yaml --output apps/account-svc
      - run: buf generate apps/oauth-svc --include-imports --template apps/oauth-svc/buf.gen.yaml --output apps/oauth-svc
      - run: buf generate apps/confirmation-of-payee-svc --include-imports --template apps/confirmation-of-payee-svc/buf.gen.yaml --output apps/confirmation-of-payee-svc
      - run: buf generate apps/payment-svc --include-imports --template apps/payment-svc/buf.gen.yaml --output apps/payment-svc
      - run: buf generate apps/ledger-svc --include-imports --template apps/ledger-svc/buf.gen.yaml --output apps/ledger-svc
      - run: buf generate apps/merchant-svc --include-imports --template apps/merchant-svc/buf.gen.yaml --output apps/merchant-svc
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
        working-directory: apps/api-server
      - name: Type check
        run: bun run typecheck
        working-directory: apps/api-server
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/api-server
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./apps/api-server/Dockerfile
