on:
  push:
    paths:
      - "apps/identity-svc/**"
      - "apps/account-svc/**"
      - "apps/merchant-svc/**"
      - "apps/payment-decision-svc/**"
      - "apps/payment-svc/**"
      - "apps/confirmation-of-payee-svc/**"
      - ".github/workflows/payment-svc.yaml"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.2"
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf generate apps/identity-svc --template apps/identity-svc/buf.gen.yaml --output apps/identity-svc
      - run: buf generate apps/account-svc --template apps/account-svc/buf.gen.yaml --output apps/account-svc
      - run: buf generate apps/merchant-svc --template apps/merchant-svc/buf.gen.yaml --output apps/merchant-svc
      - run: buf generate apps/payment-decision-svc --template apps/payment-decision-svc/buf.gen.yaml --output apps/payment-decision-svc
      - run: buf generate apps/payment-svc --template apps/payment-svc/buf.gen.yaml --output apps/payment-svc
      - run: buf generate apps/confirmation-of-payee-svc --template apps/confirmation-of-payee-svc/buf.gen.yaml --output apps/confirmation-of-payee-svc
      - name: Build
        run: go build -v apps/payment-svc/cmd/server/main.go
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/payment-svc
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./apps/payment-svc/Dockerfile
