on:
  push:
    paths:
      - "svcs/identity-svc/**"
      - "svcs/ledger-svc/**"
      - "svcs/payment-decision-svc/**"
      - ".github/workflows/payment-decision-svc.yaml"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf generate svcs/identity-svc --template svcs/identity-svc/buf.gen.yaml --output svcs/identity-svc
      - run: buf generate svcs/ledger-svc --template svcs/ledger-svc/buf.gen.yaml --output svcs/ledger-svc
      - run: buf generate svcs/payment-decision-svc --template svcs/payment-decision-svc/buf.gen.yaml --output svcs/payment-decision-svc
      - name: Build
        run: go build -v svcs/payment-decision-svc/cmd/server/main.go
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/payment-decision-svc
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./svcs/payment-decision-svc/Dockerfile